// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj1KRWf3i_Mxi0t8Mm1E_qZVAS3fsB5Pk',
    appId: '1:842447046680:web:22a60c91a7d898dfbb1b6d',
    messagingSenderId: '842447046680',
    projectId: 'testdezero',
    authDomain: 'testdezero.firebaseapp.com',
    storageBucket: 'testdezero.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhsqOxL9wKk5FBjI5e0mQrTcHMa8FDLiI',
    appId: '1:842447046680:android:b5a7ce4c759d1906bb1b6d',
    messagingSenderId: '842447046680',
    projectId: 'testdezero',
    storageBucket: 'testdezero.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNu5ul6QHEHQbucHGWSKywnMoNODnjIc',
    appId: '1:842447046680:ios:94f1c83dfc5513d5bb1b6d',
    messagingSenderId: '842447046680',
    projectId: 'testdezero',
    storageBucket: 'testdezero.firebasestorage.app',
    iosBundleId: 'com.example.testeoDezero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNu5ul6QHEHQbucHGWSKywnMoNODnjIc',
    appId: '1:842447046680:ios:94f1c83dfc5513d5bb1b6d',
    messagingSenderId: '842447046680',
    projectId: 'testdezero',
    storageBucket: 'testdezero.firebasestorage.app',
    iosBundleId: 'com.example.testeoDezero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj1KRWf3i_Mxi0t8Mm1E_qZVAS3fsB5Pk',
    appId: '1:842447046680:web:08eabbfe91d403efbb1b6d',
    messagingSenderId: '842447046680',
    projectId: 'testdezero',
    authDomain: 'testdezero.firebaseapp.com',
    storageBucket: 'testdezero.firebasestorage.app',
  );

}